### ISSUE TITLE
Bug due to Update of Roundcube

### ISSUE THREAD

**Issue by NotANormalNerd** [unstko/Roundcube-plugins#4]
there is a Bug in your Code due to the Update of Roundcube:

http://trac.roundcube.net/changeset/5758/subversion/branches/devel-framework/roundcubemail/program/include/rcmail.php

Lines 100 - 105:
The 'imap__' in Session was replaced with 'storage__' change that and everything should run fine ;-)

I needed an evening to fix your code. Thanks for the challange. Nice Plugin ;-)

**Comment by ninioperdido** [comment]
I have had the same problem. Thanks to @NotANormalNerd for the fix and @unstko for the plugin.

**Comment by sgrayban** [comment]
Plugin no longer works :( bummer

A code update hopefully ????

**Comment by TheJokr** [comment]
@sgrayban (A little late but in case you or anyone else still needs it) I fixed it for my roundcube setup in TheJokr/Roundcube-plugins@739202d

**Comment by unstko** [comment]
I don't maintain this anymore. Please see forks for updates ans solutions.
I close this issue and archive the repo.
